services:
  mysql:
    image: 'mysql:latest'
    container_name: mysql
    volumes:
      - ./database:/docker-entrypoint-initdb.d
    ports:
      - 9910:3306
    environment:
      - MYSQL_DATABASE=gorm
      - MYSQL_USER=gorm
      - MYSQL_PASSWORD=gorm
      - MYSQL_RANDOM_ROOT_PASSWORD="yes"

  redis:
    image: 'redis:latest'   
    container_name: redis
    ports:
      - 9920:6379
