// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameAddress = "address"

// Address Address information table
type Address struct {
	ID           int64          `gorm:"column:id;primaryKey;autoIncrement:true;comment:PK" json:"id"`                                       // PK
	Address      string         `gorm:"column:address;not null;comment:Address" json:"address"`                                             // Address
	AddressType  string         `gorm:"column:address_type;not null;comment:Address type" json:"address_type"`                              // Address type
	AddressOwner int64          `gorm:"column:address_owner;not null;comment:Address belongs to" json:"address_owner"`                      // Address belongs to
	Private      string         `gorm:"column:private;not null;comment:Address private key" json:"private"`                                 // Address private key
	CreatedAt    time.Time      `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP;comment:Address create time" json:"created_at"` // Address create time
	UpdatedAt    time.Time      `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP;comment:Address update time" json:"updated_at"` // Address update time
	DeletedAt    gorm.DeletedAt `gorm:"column:deleted_at;comment:Address delete time" json:"deleted_at"`                                    // Address delete time
}

// TableName Address's table name
func (*Address) TableName() string {
	return TableNameAddress
}
