// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameTask = "task"

// Task task table
type Task struct {
	ID         int64          `gorm:"column:id;primaryKey;autoIncrement:true;comment:PK" json:"id"`                                    // PK
	Userid     int64          `gorm:"column:userid;not null;comment:User id" json:"userid"`                                            // User id
	Adress     string         `gorm:"column:adress;not null;comment:wallet address" json:"adress"`                                     // wallet address
	Token      string         `gorm:"column:token;not null;comment:Token" json:"token"`                                                // Token
	Recipients string         `gorm:"column:recipients;comment:recipients list" json:"recipients"`                                     // recipients list
	Amounts    string         `gorm:"column:amounts;comment:amounts list" json:"amounts"`                                              // amounts list
	Status     int32          `gorm:"column:status;not null;comment:Task status" json:"status"`                                        // Task status
	CreatedAt  time.Time      `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP;comment:task create time" json:"created_at"` // task create time
	UpdatedAt  time.Time      `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP;comment:task update time" json:"updated_at"` // task update time
	DeletedAt  gorm.DeletedAt `gorm:"column:deleted_at;comment:task delete time" json:"deleted_at"`                                    // task delete time
}

// TableName Task's table name
func (*Task) TableName() string {
	return TableNameTask
}
