// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	address "towin/biz/router/address"
	task "towin/biz/router/task"
	users "towin/biz/router/users"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	users.Register(r)

	task.Register(r)

	address.Register(r)
}
